"""
    scripts/gen_regexlexer_optimizations.py
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Regenerate the preprocessed RegexLexer token tables used at import time.

    :copyright: Copyright 2006-present by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""

from importlib import import_module
from pathlib import Path
import sys


top_src_dir = Path(__file__).parent.parent
pygments_package = top_src_dir / 'pygments'
sys.path.insert(0, str(pygments_package.parent.resolve()))

from pygments.lexers._mapping import LEXERS  # noqa: E402


def main():
    module_names = sorted({module_name for module_name, _, _, _, _ in LEXERS.values()})
    imports = '\n'.join(
        f"from {module_name} import *" if module_name.startswith('pygments.lexers.') else f"import {module_name}"
        for module_name in module_names
    )

    content = f'''# Automatically generated by scripts/gen_regexlexer_optimizations.py.
# DO NOT EDIT BY HAND; run `tox -e regexlexer-optimizations` instead.

from importlib import import_module

from pygments.lexer import RegexLexer

{imports}


def apply_optimizations():
    for module_name in {module_names!r}:
        module = import_module(module_name)
        for obj in vars(module).values():
            if isinstance(obj, type) and issubclass(obj, RegexLexer) and obj is not RegexLexer:
                obj._ensure_tokens()
'''
    output_path = pygments_package / 'lexers' / '_generated_regexlexer_optimizations.py'
    output_path.write_text(content, encoding='utf8')
    print(f'Wrote {output_path}')


if __name__ == '__main__':
    main()
