"""
    scripts/gen_regexlexer_optimizations.py
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Regenerate the precomputed RegexLexer merge plans used at import time.

    The expensive part of :class:`~pygments.lexer.RegexLexer` startup is the
    decision of *which* consecutive simple rules to merge into one combined
    regex (see ``RegexLexerMeta._compute_merge_plan``).  That decision depends
    only on the static token definitions, so it is computed here at build time
    and written to ``pygments/lexers/_generated_regexlexer_optimizations.py`` as
    a compact table of integer index groupings.  At import time each lexer looks
    up its plan and applies it, compiling the merged regexes lazily on first
    use; no merge analysis is done at runtime.

    :copyright: Copyright 2006-present by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""

from importlib import import_module
from pathlib import Path
import sys


top_src_dir = Path(__file__).parent.parent
pygments_package = top_src_dir / 'pygments'
sys.path.insert(0, str(pygments_package.parent.resolve()))

from pygments.lexer import RegexLexer  # noqa: E402
from pygments.lexers._mapping import LEXERS  # noqa: E402


def _plan_for_lexer(cls):
    """Return ``{state: plan}`` for the states of *cls* that have merges."""
    cls._all_tokens = {}
    cls._tmpname = 0
    # Process without merging, then compute the merge plan for each state.
    processed = cls.process_tokendef('', cls.get_tokendefs(), merge=False)
    plan = {}
    for state, rules in processed.items():
        state_plan = cls._compute_merge_plan(rules)
        # Only states that actually merge something (a grouped segment, i.e. a
        # list) need to be stored; the rest are left untouched at import time.
        if any(type(seg) is list for seg in state_plan):
            plan[state] = state_plan
    return plan


def main():
    module_names = sorted({module_name for module_name, _, _, _, _ in LEXERS.values()})
    for module_name in module_names:
        import_module(module_name)

    plans = {}
    for module_name in module_names:
        module = import_module(module_name)
        lexer_classes = [
            obj for obj in vars(module).values()
            if isinstance(obj, type)
            and issubclass(obj, RegexLexer)
            and obj is not RegexLexer
            and obj.__module__ == module_name
        ]
        lexer_classes.sort(key=lambda cls: cls.__qualname__)
        for cls in lexer_classes:
            if getattr(cls, 'token_variants', False):
                continue
            # Store an entry for every processed lexer (possibly empty) so that
            # a missing key unambiguously means "not a builtin lexer" and falls
            # back to computing the merge at runtime.
            plans[f'{module_name}.{cls.__qualname__}'] = _plan_for_lexer(cls)

    body = '\n'.join(f'    {key!r}: {plan!r},'
                     for key, plan in sorted(plans.items()))

    content = f'''\
# Automatically generated by scripts/gen_regexlexer_optimizations.py.
# DO NOT EDIT BY HAND; run `tox -e regexlexer-optimizations` instead.
#
# ``MERGE_PLANS`` maps ``"<module>.<LexerClass>"`` to a per-state merge plan.
# A plan is ``{{state: [segment, ...]}}`` where each segment is either an int
# (the index of a processed rule kept as-is) or a list of consecutive indices
# whose rules are merged into a single combined regex.  See
# ``pygments.lexer.RegexLexerMeta._compute_merge_plan`` for how plans are built
# and ``._apply_merge_plan`` for how they are applied.

MERGE_PLANS = {{
{body}
}}
'''

    output_path = pygments_package / 'lexers' / '_generated_regexlexer_optimizations.py'
    output_path.write_text(content, encoding='utf8')
    print(f'Wrote {output_path} ({len(plans)} lexers)')


if __name__ == '__main__':
    main()
